<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../MailMeUp.Core/MailMeUp.Core.csproj" />
    <ProjectReference Include="../MailMeUp.Security/MailMeUp.Security.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" />
  </ItemGroup>
</Project>
