using MailMeUp.Core;
using MailMeUp.Storage;
using Microsoft.Data.Sqlite;
using Xunit;

namespace MailMeUp.Tests;

public sealed class AccountStoreTests : IDisposable
{
    private readonly string _directory = Path.Combine(Path.GetTempPath(), "MailMeUp.Tests", Guid.NewGuid().ToString("N"));

    [Fact]
    public async Task FreshRegistryReadDoesNotCreateFiles()
    {
        Assert.Empty(await new SqliteAccountStore(_directory).ListAsync());
        Assert.False(Directory.Exists(_directory));
    }

    [Fact]
    public async Task SameAddressAcrossProvidersRetainsSeparateAccountIds()
    {
        var store = new SqliteAccountStore(_directory);
        await store.SaveAsync(new("b", "microsoft", "Work", "person@example.test"));
        await store.SaveAsync(new("a", "google", "Personal", "person@example.test"));

        var persisted = await new SqliteAccountStore(_directory).ListAsync();
        Assert.Equal(["a", "b"], persisted.Select(account => account.Id));
        Assert.Equal(["google", "microsoft"], persisted.Select(account => account.Provider));
    }

    [Fact]
    public async Task SaveUpdatesOnlyTheRequestedAccountAndTreatsInputAsData()
    {
        var store = new SqliteAccountStore(_directory);
        var opaque = "id'; DROP TABLE accounts; --";
        await store.SaveAsync(new(opaque, "google", "Old label", "person@example.test"));
        await store.SaveAsync(new("other", "google", "Other", "other@example.test"));
        await store.SaveAsync(new(opaque, "google", "O'Brien", "person@example.test"));

        var accounts = await store.ListAsync();
        Assert.Equal(2, accounts.Count);
        Assert.Equal("O'Brien", accounts.Single(account => account.Id == opaque).DisplayName);
        Assert.Equal("Other", accounts.Single(account => account.Id == "other").DisplayName);
    }

    [Fact]
    public async Task SeparateInstancesCanInitializeAndWriteConcurrently()
    {
        await Task.WhenAll(Enumerable.Range(0, 6).Select(index => Task.Run(async () =>
            await new SqliteAccountStore(_directory).SaveAsync(new(index.ToString(), "google", "Sample", "sample@example.test")))));
        Assert.Equal(6, (await new SqliteAccountStore(_directory).ListAsync()).Count);
    }

    [Fact]
    public async Task NewerSchemaIsRejectedWithoutChangingTheDatabase()
    {
        var store = new SqliteAccountStore(_directory);
        await store.SaveAsync(new("a", "google", "Sample", "sample@example.test"));
        await using (var connection = new SqliteConnection($"Data Source={Path.Combine(_directory, "accounts.db")};Pooling=False"))
        {
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = "PRAGMA user_version = 999";
            await command.ExecuteNonQueryAsync();
        }

        await Assert.ThrowsAsync<InvalidOperationException>(() => store.ListAsync());
        await Assert.ThrowsAsync<InvalidOperationException>(() => store.SaveAsync(new("b", "google", "Sample", "sample@example.test")));
    }

    [Theory]
    [InlineData("relative/path")]
    [InlineData("..")]
    public void RelativeOverrideIsRejected(string path) => Assert.Throws<ArgumentException>(() => DataDirectory.Resolve(path));

    [Fact]
    public async Task InvalidAccountDoesNotCreateARegistry()
    {
        await Assert.ThrowsAsync<ArgumentException>(() => new SqliteAccountStore(_directory).SaveAsync(new("", "google", "Sample", "sample@example.test")));
        Assert.False(Directory.Exists(_directory));
    }

    public void Dispose()
    {
        // This exact directory is generated by the fixture beneath the OS temporary directory.
        if (Directory.Exists(_directory))
        {
            Directory.Delete(_directory, recursive: true);
        }
    }
}
