#!/usr/bin/env python3
"""Create or verify a deterministic inventory from the restored CLI package graph."""

import argparse
import json
from pathlib import Path
import shutil
import xml.etree.ElementTree as ET


def metadata(path):
    root = ET.parse(path).getroot()
    for element in root.iter():
        element.tag = element.tag.split("}")[-1]
    return root.find("metadata")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--copy-to", type=Path)
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    graph = json.loads((repo / "src/MailMeUp.Cli/obj/project.assets.json").read_text(encoding="utf-8"))
    roots = [Path(root) for root in graph["packageFolders"]]
    rows = ["# Runtime dependency inventory", "", "Generated by `python scripts/export-notices.py` from the restored CLI dependency graph.", "",
            "This lists package dependencies, including transitive dependencies. Self-contained distributions also include the .NET runtime.", "",
            "| Package | Version | Declared license |", "| --- | --- | --- |"]
    if args.copy_to:
        args.copy_to.mkdir(parents=True, exist_ok=True)
    for key, entry in sorted(graph["libraries"].items(), key=lambda item: item[0].lower()):
        if entry["type"] != "package":
            continue
        name, version = key.split("/", 1)
        folder = next((root / entry["path"] for root in roots if (root / entry["path"]).is_dir()), None)
        if folder is None:
            raise RuntimeError(f"Package not restored: {key}")
        spec = metadata(next(folder.glob("*.nuspec")))
        license_element = spec.find("license")
        if license_element is None or not license_element.text:
            raise RuntimeError(f"Review missing license metadata: {key}")
        license_name = license_element.text.strip()
        rows.append(f"| {name} | {version} | {license_name} |")
        if args.copy_to:
            destination = args.copy_to / f"{name}.{version}"
            destination.mkdir(exist_ok=True)
            shutil.copy2(next(folder.glob("*.nuspec")), destination)
            for file in folder.iterdir():
                if file.is_file() and any(word in file.name.lower() for word in ("license", "notice", "copying")):
                    shutil.copy2(file, destination / file.name)
            if license_element.get("type") == "file":
                license_file = (folder / license_name).resolve(strict=True)
                if not license_file.is_relative_to(folder.resolve()):
                    raise RuntimeError(f"Unsafe license path: {key}")
                shutil.copy2(license_file, destination / license_file.name)
    content = "\n".join(rows) + "\n"
    inventory = repo / "docs/DEPENDENCIES.md"
    if args.check:
        if not inventory.exists() or inventory.read_text(encoding="utf-8") != content:
            raise RuntimeError("Run python scripts/export-notices.py and commit docs/DEPENDENCIES.md")
    else:
        inventory.write_text(content, encoding="utf-8", newline="\n")
    print("PASS: runtime dependency inventory matches restored packages.")


if __name__ == "__main__":
    main()
